module.exports = data = {
    name: "BaseProfile",
    version: "1.0.1",
    author: "hitomihiumi",
    data: {
        width: 600,
        height: 600,
        errorImage: null,
        structureType: 'canvas',
        methods: [],
        layers: [
            {
                shadow: {},
                angle: 0,
                structureType: 'layer',
                fill: false,
                type: 'ellipseimage',
                x: 0,
                y: 0,
                width: 600,
                height: 600,
                radius: 28,
                image: '#{background}#'
            },
            {
                shadow: {},
                angle: 0,
                structureType: 'layer',
                fill: true,
                type: 'ellipse',
                x: 0,
                y: 0,
                width: 600,
                height: 600,
                radius: 28,
                color: '#000',
                alpha: 0.4
            },
            {
                shadow: {},
                angle: 0,
                structureType: 'layer',
                fill: false,
                type: 'ellipse',
                x: 1,
                y: 1,
                width: 598,
                height: 598,
                radius: 28,
                color: '#{borderColor}#',
                stroke: 2
            },
            {
                shadow: {},
                angle: 0,
                structureType: 'layer',
                fill: false,
                type: 'ellipseimage',
                x: 20,
                y: 170,
                width: 150,
                height: 150,
                radius: 50,
                image: '#{avatar}#'
            },
            {
                shadow: {},
                angle: 0,
                structureType: 'layer',
                fill: false,
                type: 'ellipse',
                x: 20,
                y: 170,
                width: 150,
                height: 150,
                radius: 50,
                color: '#fff',
                stroke: 1.5
            },
            {
                shadow: {},
                angle: 0,
                structureType: 'layer',
                fill: true,
                type: 'ellipse',
                x: 190,
                y: 286,
                width: 385,
                height: 35,
                radius: 17.5,
                color: '#fff'
            },
            {
                shadow: {},
                angle: 0,
                structureType: 'layer',
                fill: true,
                type: 'ellipse',
                x: 192.5,
                y: 288.5,
                width: `((#{xp}# / #{neededXp}#) * 385)`,
                height: 30,
                radius: 15,
                color: '#{progressColor}#'
            },
            {
                shadow: {},
                angle: 0,
                structureType: 'layer',
                fill: true,
                type: 'circle',
                x: 140,
                y: 290,
                radius: 20,
                color: '#{progressColor}#'
            },
            {
                shadow: {},
                angle: 0,
                structureType: 'layer',
                fill: false,
                type: 'circle',
                x: 140,
                y: 290,
                radius: 20,
                color: '#fff',
                stroke: 1.5
            },
            {
                shadow: {},
                angle: 0,
                structureType: 'layer',
                fill: true,
                type: 'text',
                font: 'OpenSans',
                size: 25,
                weight: 'bold',
                x: 80,
                y: 380,
                text: 'About',
                color: '#{textColor}#',
                align: 'center'
            },
            {
                shadow: {},
                angle: 0,
                structureType: 'layer',
                fill: true,
                type: 'text',
                font: 'OpenSans',
                size: 30,
                weight: 'bold',
                x: 190,
                y: 281,
                text: '#{name}#',
                color: '#{textColor}#',
                align: 'left'
            },
            {
                shadow: {},
                angle: 0,
                structureType: 'layer',
                fill: true,
                type: 'text',
                font: 'OpenSans',
                size: 25,
                weight: 'bold',
                x: 573,
                y: 281,
                text: '#{xp}#/#{neededXp}#',
                color: '#{textColor}#',
                align: 'end'
            },
            {
                shadow: {},
                angle: 0,
                structureType: 'layer',
                fill: true,
                type: 'text',
                font: 'OpenSans',
                size: 37,
                weight: 'bold',
                x: 160,
                y: 309,
                text: '#{level}#',
                color: '#{textColor}#',
                align: 'center',
                baseline: 'middle'
            },
            {
                shadow: {},
                angle: 0,
                structureType: 'layer',
                fill: true,
                type: 'text',
                font: 'OpenSans',
                size: 35,
                weight: 'bold',
                x: 575,
                y: 45,
                text: '#{position}#',
                color: '#{textColor}#',
                align: 'end'
            },
            {
                shadow: {},
                angle: 0,
                structureType: 'layer',
                fill: true,
                type: 'text',
                font: 'OpenSans',
                size: 25,
                weight: 'bold',
                x: 20,
                y: 386,
                text: '#{biography}#',
                color: '#{textColor}#',
                align: 'start',
                multiline: true,
                width: 560,
                height: 200
            },
            {
                shadow: {},
                angle: 0,
                structureType: 'layer',
                fill: false,
                type: 'ellipse',
                x: 1,
                y: 1,
                width: 598,
                height: 340,
                radius: 28,
                color: '#{borderColor}#',
                stroke: 2.5
            },
            {
                shadow: {},
                angle: 0,
                structureType: 'layer',
                fill: false,
                type: 'ellipse',
                x: 1,
                y: 340,
                width: 598,
                height: 260,
                radius: 28,
                color: '#{borderColor}#',
                stroke: 2.5
            }
        ]
    }
}