module.exports = RankData = {
    name: "BaseRank",
    version: "1.0.0",
    author: "hitomihiumi",
    fontURL: "standard font",
    data: {
        width: 600,
        height: 200,
        errorImage: null,
        structureType: 'canvas',
        methods: [],
        layers: [
            {
                shadow: {},
                angle: 0,
                structureType: 'layer',
                fill: false,
                type: 'ellipseimage',
                x: 0,
                y: 0,
                width: 600,
                height: 200,
                radius: 50,
                image: '#{background}#'
            },
            {
                shadow: {},
                angle: 0,
                structureType: 'layer',
                fill: true,
                type: 'ellipse',
                x: 0,
                y: 0,
                width: 600,
                height: 200,
                radius: 50,
                color: '#000',
                alpha: 0.4
            },
            {
                shadow: {},
                angle: 0,
                structureType: 'layer',
                fill: false,
                type: 'ellipse',
                x: 1,
                y: 1,
                width: 598,
                height: 198,
                radius: 50,
                color: '#{borderColor}#',
                stroke: 2
            },
            {
                shadow: {},
                angle: 0,
                structureType: 'layer',
                fill: false,
                type: 'ellipseimage',
                x: 25,
                y: 25,
                width: 150,
                height: 150,
                radius: 50,
                image: '#{avatar}#'
            },
            {
                shadow: {},
                angle: 0,
                structureType: 'layer',
                fill: false,
                type: 'ellipse',
                x: 25,
                y: 25,
                width: 150,
                height: 150,
                radius: 50,
                color: '#fff',
                stroke: 1.5
            },
            {
                shadow: {},
                angle: 0,
                structureType: 'layer',
                fill: true,
                type: 'ellipse',
                x: 190,
                y: 125,
                width: 365,
                height: 35,
                radius: 17.5,
                color: '#fff'
            },
            {
                shadow: {},
                angle: 0,
                structureType: 'layer',
                fill: true,
                type: 'ellipse',
                x: 192.5,
                y: 127.5,
                width: `((#{xp}# / #{neededXp}#) * 365)`,
                height: 30,
                radius: 15,
                color: '#{progressColor}#'
            },
            {
                shadow: {},
                angle: 0,
                structureType: 'layer',
                fill: true,
                type: 'circle',
                x: 140,
                y: 140,
                width: 20,
                color: '#{progressColor}#'
            },
            {
                shadow: {},
                angle: 0,
                structureType: 'layer',
                fill: false,
                type: 'circle',
                x: 140,
                y: 140,
                width: 20,
                color: '#fff',
                stroke: 1.5
            },
            {
                shadow: {},
                angle: 0,
                structureType: 'layer',
                fill: true,
                type: 'text',
                font: 'OpenSans',
                size: 25,
                weight: 'bold',
                x: 200,
                y: 120,
                text: '#{name}#',
                color: '#{textColor}#',
                align: 'left'
            },
            {
                shadow: {},
                angle: 0,
                structureType: 'layer',
                fill: true,
                type: 'text',
                font: 'OpenSans',
                size: 20,
                weight: 'bold',
                x: 550,
                y: 120,
                text: '#{xp}#/#{neededXp}#',
                color: '#fff',
                align: 'right'
            },
            {
                shadow: {},
                angle: 0,
                structureType: 'layer',
                fill: true,
                type: 'text',
                font: 'OpenSans',
                size: '#{levelFontSize}#',
                weight: 'bold',
                x: 160,
                y: 160,
                text: '#{level}#',
                color: '#fff',
                baseline: 'middle',
                align: 'center'
            }
        ]
    }
}